[versions]
agp = "8.8.0"
kotlin = "2.0.20"
material = "1.12.0"
appcompat = "1.7.0"
constraintlayout = "2.2.0"
maplibre = "11.7.1"
legacySupportV4 = "1.0.0"
recyclerview = "1.4.0"
play-services-location = "21.0.1"
mapbox-android-plugin-localization-v9 = "3.0.2"
mapbox-android-plugin-markerview-v9 = "3.0.2"
glide = "4.16.0"
cardview = "1.0.0"
lifecycle = "2.2.0"
gson = "2.8.9"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"


[libraries]
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
lifecycle = { group = "androidx.lifecycle", name = "lifecycle-extensions", version.ref = "lifecycle" }
cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
google-play-service-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "play-services-location" }
maplibre = { group = "org.maplibre.gl", name = "android-sdk", version.ref = "maplibre" }
mapbox-android-plugin-localization = { group = "org.maplibre.gl", name = "android-plugin-localization-v9", version.ref = "mapbox-android-plugin-localization-v9" }
mapbox-android-plugin-markerview = { group = "org.maplibre.gl", name = "android-plugin-markerview-v9", version.ref = "mapbox-android-plugin-markerview-v9" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-legacy-support-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacySupportV4" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }

